-   Explore columns
-   Figure out metric to quantify "safety"
    -   Crime per 1000: 1000 * (total crime / population)
    -   Weighted crime (weight violent crimes higher than property theft)
-   Sort table by this metric
-   Inspect "Delaware County Sheriff's Office"
-   Compare it with other Ohio counties

## Libraries

In [2]:
import pandas as pd
import sys, os
config_dir = os.path.abspath(os.path.join(os.getcwd(), '..\\config'))
sys.path.append(config_dir)
from ohio_data import ohio_counties, ohio_cities

## Data Ingestion

In [3]:
table = pd.read_excel(r'S:\1. Repositories\ohio-crime-scrapper\data\downloads\ohio_crime_report.ods',
                      engine='odf')

## Feature Engineering

In [ ]:
#drop empty column
table.drop(columns=['Unnamed: 11'], inplace = True)
#rename to county level pop since we will add city level as well
table.rename(columns={'Population': 'County Population'}, 
             inplace = True)
#report is pulled from 2022
table['Year'] = '2022'
#total crime
table['Total Crime'] = table['ViolentCrimeTotal'] + table['PropertyCrimeTotal']
#crime per 1000
table['Crime per 1000'] = (table['Total Crime'] / table['Population']) * 1000
#creat county column 
table['County'] = table['AgencyName'].str.split('Sheriff').str[0].str.strip()
#add city level data
table["City"] = table["County"].map(ohio_counties)
table = table.explode("City", ignore_index=True)
#add city population data

,AgencyName,Population,ViolentCrimeTotal,Murder,Rape,Robbery,AggravatedAssault,PropertyCrimeTotal,Burglary,LarcenyTheft,MotorVehicleTheft,Unnamed: 11,Year,Total Crime,Crime per 1000,County,City
0,Adams County Sheriff's Office,20847,4,0,1,0,3,40,17,17,6,NaN,2022,44,2.110615,Adams County,West Union
1,Adams County Sheriff's Office,20847,4,0,1,0,3,40,17,17,6,NaN,2022,44,2.110615,Adams County,Peebles
2,Adams County Sheriff's Office,20847,4,0,1,0,3,40,17,17,6,NaN,2022,44,2.110615,Adams County,Seaman
3,Allen County Sheriff's Office,22928,52,1,9,5,37,359,81,255,23,NaN,2022,411,17.925680,Allen County,Lima
4,Allen County Sheriff's Office,22928,52,1,9,5,37,359,81,255,23,NaN,2022,411,17.925680,Allen County,Beaverdam
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,Wayne County Sheriff's Office,61796,26,0,7,0,19,309,81,195,33,NaN,2022,335,5.421063,Wayne County,Rittman
243,Wayne County Sheriff's Office,61796,26,0,7,0,19,309,81,195,33,NaN,2022,335,5.421063,Wayne County,Creston
244,Wood County Sheriff's Office,29158,17,0,10,0,7,161,22,123,16,NaN,2022,178,6.104671,Wood County,Bowling Green
245,Wood County Sheriff's Office,29158,17,0,10,0,7,161,22,123,16,NaN,2022,178,6.104671,Wood County,Oregon
246,Wood County Sheriff's Office,29158,17,0,10,0,7,161,22,123,16,NaN,2022,178,6.104671,Wood County,Perrysburg

In [7]:
table

,AgencyName,Population,ViolentCrimeTotal,Murder,Rape,Robbery,AggravatedAssault,PropertyCrimeTotal,Burglary,LarcenyTheft,MotorVehicleTheft,Unnamed: 11,Year,Total Crime,Crime per 1000,County
0,Adams County Sheriff's Office,20847,4,0,1,0,3,40,17,17,6,NaN,2022,44,2.110615,Adams County
1,Allen County Sheriff's Office,22928,52,1,9,5,37,359,81,255,23,NaN,2022,411,17.925680,Allen County
2,Ashland County Sheriff's Office,29377,21,2,9,0,10,37,11,18,8,NaN,2022,58,1.974334,Ashland County
3,Ashtabula County Sheriff's Office,50240,24,1,5,1,17,289,46,195,48,NaN,2022,313,6.230096,Ashtabula County
4,Athens County Sheriff's Office,29101,7,2,2,0,3,161,31,109,21,NaN,2022,168,5.772997,Athens County
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,Vinton County Sheriff's Office,10125,16,2,6,0,8,56,12,35,9,NaN,2022,72,7.111111,Vinton County
68,Warren County Sheriff's Office,100673,25,0,11,6,8,415,30,358,27,NaN,2022,440,4.370586,Warren County
69,Washington County Sheriff's Office,36671,16,0,8,2,6,187,41,122,24,NaN,2022,203,5.535709,Washington County
70,Wayne County Sheriff's Office,61796,26,0,7,0,19,309,81,195,33,NaN,2022,335,5.421063,Wayne County
71,Wood County Sheriff's Office,29158,17,0,10,0,7,161,22,123,16,NaN,2022,178,6.104671,Wood County

In [3]:
features = ['AgencyName', 'Population', 'ViolentCrimeTotal', 'PropertyCrimeTotal', 'Total Crime', 'Crime per 1000']
table[table['AgencyName'].isin(["Delaware County Sheriff's Office", "Franklin County Sheriff's Office"])][features]

,AgencyName,Population,ViolentCrimeTotal,PropertyCrimeTotal,Total Crime,Crime per 1000
18,Delaware County Sheriff's Office,101001,42,601,643,6.366274
22,Franklin County Sheriff's Office,55803,69,246,315,5.644858

In [ ]:
#split agency name by Sheriff's to gert county
#do a lookup to figure out location